// User Async Key
export const USER_LOCAL_STORAGE = 'USER_LOCAL_STORAGE';
export const JOURNAL_LOCAL_STORAGE = 'JOURNAL_LOCAL_STORAGE';
export const PRODUCTS_LOCAL_STORAGE = 'PRODUCTS_LOCAL_STORAGE';
export const CONTENT_LOCAL_STORAGE = 'CONTENT_LOCAL_STORAGE';
export const FIRST_TIME = 'FIRST_TIME';
export const GENERAL_LOCAL_STORAGE = 'GENERAL_LOCAL_STORAGE';

